Exit code: 0
Wall time: 1.2 seconds
Output:
export const adminHtml = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>IG Store Â· Reel Replies</title>
<style>
:root{font-family:Inter,system-ui,sans-serif;color:#1c1917;background:#f7f5f2}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1100px;margin:auto;padding:32px 18px}.card{background:#fff;border:1px solid #e7e3dd;border-radius:16px;padding:20px;margin:16px 0;box-shadow:0 1px 2px #00000008}h1{margin:0 0 6px}h2{font-size:18px;margin:0 0 14px}.muted{color:#6b655d}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.full{grid-column:1/-1}label{display:block;font-size:13px;font-weight:700;margin-bottom:6px}input,textarea,select,button{font:inherit}input,textarea,select{width:100%;padding:10px;border:1px solid #cfc8bf;border-radius:9px;background:#fff}textarea{min-height:100px;resize:vertical}button{background:#1d4ed8;color:#fff;border:0;border-radius:9px;padding:10px 14px;font-weight:700;cursor:pointer}button.secondary{background:#eee9e2;color:#302b25}button.danger{background:#b91c1c}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.rule{border-top:1px solid #eee8e1;padding:14px 0;display:flex;justify-content:space-between;gap:12px}.rule:first-child{border-top:0}.pill{background:#e9f3ff;color:#1e40af;border-radius:20px;padding:3px 9px;font-size:12px}.hidden{display:none}#notice{min-height:22px;font-weight:600}.ok{color:#15803d}.error{color:#b91c1c}@media(max-width:680px){.grid{grid-template-columns:1fr}.full{grid-column:auto}.wrap{padding:18px 12px}}
</style></head><body><main class="wrap"><h1>Reel Reply Control Panel</h1><p class="muted">Manage public comment replies and private DMs Reel-wise. Use <code>{{username}}</code> and <code>{{media_id}}</code> in messages.</p>
<section id="login" class="card"><h2>Secure sign in</h2><div class="row"><input id="password" type="password" placeholder="Panel password" autocomplete="current-password"><button id="loginBtn">Sign in</button></div><p id="loginError" class="error"></p></section>
<section id="app" class="hidden"><div class="card"><div class="row" style="justify-content:space-between"><div><h2>Automation status</h2><p id="stats" class="muted">Loadingâ€¦</p></div><button class="secondary" id="logoutBtn">Sign out</button></div></div>
<section class="card"><h2 id="formTitle">Add or edit rule</h2><form id="ruleForm" class="grid"><div><label>Reel media ID</label><input id="mediaId" required placeholder="Paste Reel media ID, or use default"></div><div><label>Rule status</label><select id="enabled"><option value="true">Enabled</option><option value="false">Disabled</option></select></div><div class="full"><label>Trigger keywords (comma separated)</label><input id="keywords" placeholder="link, price, order â€” leave empty to reply to every top-level comment"></div><div><label>Public comment reply</label><textarea id="publicReply" required></textarea></div><div><label>Private DM reply</label><textarea id="privateReply" required></textarea></div><div class="full row"><button type="submit">Save rule</button><button class="secondary" type="button" id="resetBtn">New rule</button><span id="notice"></span></div></form></section>
<section class="card"><h2>Saved rules</h2><div id="rules">Loadingâ€¦</div></section></section></main>
<script>
const $=id=>document.getElementById(id);let rules=[];const api=(url,opts={})=>fetch(url,{headers:{'content-type':'application/json',...(opts.headers||{})},...opts}).then(async r=>{const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed');return j});
function note(msg,err=false){$('notice').textContent=msg;$('notice').className=err?'error':'ok'}
function form(rule){$('formTitle').textContent=rule?'Edit rule':'Add or edit rule';$('mediaId').value=rule?.mediaId||'';$('enabled').value=String(rule?.enabled??true);$('keywords').value=(rule?.keywords||[]).join(', ');$('publicReply').value=rule?.publicReply||'';$('privateReply').value=rule?.privateReply||'';window.scrollTo({top:0,behavior:'smooth'})}
function render(){const box=$('rules');if(!rules.length){box.textContent='No custom rules yet. The built-in default is currently active.';return}box.innerHTML='';rules.forEach(r=>{const el=document.createElement('div');el.className='rule';const info=document.createElement('div');info.innerHTML='<strong>'+r.mediaId+'</strong> <span class="pill">'+(r.enabled?'Enabled':'Disabled')+'</span><br><span class="muted">Keywords: '+(r.keywords.length?r.keywords.join(', '):'All top-level comments')+'</span>';const actions=document.createElement('div');const edit=document.createElement('button');edit.className='secondary';edit.textContent='Edit';edit.onclick=()=>form(r);const del=document.createElement('button');del.className='danger';del.textContent='Delete';del.onclick=async()=>{if(!confirm('Delete this custom rule?'))return;try{await api('/api/admin/rules/'+encodeURIComponent(r.mediaId),{method:'DELETE'});await load();note('Rule deleted.')}catch(e){note(e.message,true)}};actions.append(edit,del);el.append(info,actions);box.append(el)})}
async function load(){try{const [ruleData,overview]=await Promise.all([api('/api/admin/rules'),api('/api/admin/overview')]);rules=ruleData.rules;render();$('stats').textContent='Processed: '+overview.completed+' Â· Waiting/retrying: '+overview.pending+' Â· Failed: '+overview.failed}catch(e){if(e.message==='Unauthorized'){location.reload();return}note(e.message,true)}}
$('loginBtn').onclick=async()=>{try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({password:$('password').value})});$('login').classList.add('hidden');$('app').classList.remove('hidden');load()}catch(e){$('loginError').textContent=e.message}};
$('password').addEventListener('keydown',e=>{if(e.key==='Enter')$('loginBtn').click()});$('logoutBtn').onclick=async()=>{await api('/api/admin/logout',{method:'POST'});location.reload()};$('resetBtn').onclick=()=>form();$('ruleForm').onsubmit=async e=>{e.preventDefault();const mediaId=$('mediaId').value.trim();try{await api('/api/admin/rules/'+encodeURIComponent(mediaId),{method:'PUT',body:JSON.stringify({enabled:$('enabled').value==='true',keywords:$('keywords').value.split(',').map(x=>x.trim()).filter(Boolean),publicReply:$('publicReply').value,privateReply:$('privateReply').value})});note('Rule saved. It will apply to new comments immediately.');await load();form()}catch(err){note(err.message,true)}};
api('/api/admin/overview').then(()=>{$('login').classList.add('hidden');$('app').classList.remove('hidden');load()}).catch(()=>{});
</script></body></html>`;

